
export const menuList =[
  {
    id: 1,
    variant: 'food',
    menuItem: 'Soups',
  },
  {
    id: 2,
    variant: 'food',
    menuItem: 'Appetizers',
  },
  {
    id: 3,
    variant: 'food',
    menuItem: 'Salads',
  },
  {
    id: 4,
    variant: 'food',
    menuItem: 'Sandwiches',
  },
  {
    id: 5,
    variant: 'food',
    menuItem: 'Main Course',
  },
  {
    id: 6,
    variant: 'food',
    menuItem: 'Sauces & Extras',
  },
  {
    id: 7,
    variant: 'food',
    menuItem: 'Desert',
  },
  {
    id: 8,
    variant: 'drinks',
    menuItem: 'Cocktails',
  },
  {
    id: 9,
    variant: 'drinks',
    menuItem: 'Whiskey',
  },
  {
    id: 23,
    variant: 'drinks',
    menuItem: 'Rum',
  },
  {
    id: 10,
    variant: 'drinks',
    menuItem: 'Gin',
  },
  {
    id: 11,
    variant: 'drinks',
    menuItem: 'Vodka',
  },
  {
    id: 12,
    variant: 'drinks',
    menuItem: 'Vermouth',
  },
  {
    id: 13,
    variant: 'drinks',
    menuItem: 'Tequila',
  },
  {
    id: 14,
    variant: 'drinks',
    menuItem: 'Brandy & Cognac',
  },
  {
    id: 15,
    variant: 'drinks',
    menuItem: 'Liqueur & Bitters',
  },
  {
    id: 17,
    variant: 'drinks',
    menuItem: 'Wine',
  },
  {
    id: 18,
    variant: 'drinks',
    menuItem: 'Beer',
  },
  {
    id: 19,
    variant: 'drinks',
    menuItem: 'Soft Drinks',
  },
  {
    id: 20,
    variant: 'drinks',
    menuItem: 'Mocktails',
  },
  {
    id: 21,
    variant: 'drinks',
    menuItem: 'Tea & Coffee',
  },
  {
    id: 22,
    variant: 'drinks',
    menuItem: 'Snacks',
  },
]

export const products =[
  {
    id: 1,
    subVariant:'food',
    variant: 'Soups',
    title:'Soup of The Day',
    counter:'0',
    price:'1500',
  },
  {
    id: 2,
    subVariant:'food',
    variant: 'Appetizers',
    title:'Fruit Platter',
    counter:'0',
    price:'4800',
    ingredients:'5 types of seasonal fruit',
  },
  {
    id: 3,
    subVariant:'food',
    variant: 'Appetizers',
    title:'Cheese Platter',
    counter:'0',
    price:'3700',
    ingredients:'parmesan, cheddar, bri, feta, rockford, honey',
  },
  {
    id: 4,
    subVariant:'food',
    variant: 'Appetizers',
    title:'Meat Platter',
    counter:'0',
    price:'5000',
    ingredients:'prosciutto, pancetta, chorizo, hunter sausage, jalapeno, olives',
  },
  {
    id: 5,
    subVariant:'food',
    variant: 'Appetizers',
    counter:'0',
    title:'Mix Platter',
    price:'8000',
    ingredients:'parmesan, cheddar, bri, feta, prosciutto, pancetta, chorizo, hunter sausage, honey, jalapeno,olives',
  },
  {
    id: 6,
    subVariant:'food',
    variant: 'Appetizers',
    counter:'0',
    title:'Dip Platter',
    price:'3000',
    ingredients:'Strained yogurt, mutabal, hummus',
  },
  {
    id: 7,
    subVariant:'food',
    variant: 'Appetizers',
    counter:'0',
    title:'Chicken Nuggets',
    price:'1800',
    ingredients:'Fried chicken breast, cocktail sauce',
  },
  {
    id: 8,
    subVariant:'food',
    variant: 'Appetizers',
    counter:'0',
    title:'Grilled Vegetables',
    price:'1800',
    ingredients:'pepper, tomato, mushroom, eggplant, broccoli, zucchini, sauce',
  },
  {
    id: 9,
    subVariant:'food',
    variant: 'Appetizers',
    counter:'0',
    title:'Nachos',
    price:'3500',
    ingredients:'Corn chips, cheese, salsa, guacamole, sour cream, jalapeno',
  },
  {
    id: 10,
    subVariant:'food',
    variant: 'Appetizers',
    counter:'0',
    title:'Beef',
    price:'4500',
    ingredients:'Beef, corn chips, cheese, salsa, guacamole, sour cream, jalapeno',
  },
  {
    id: 11,
    subVariant:'food',
    variant: 'Appetizers',
    counter:'0',
    title:'Fries',
    price:'1000',
  },
  {
    id: 12,
    subVariant:'food',
    variant: 'Salads',
    counter:'0',
    title:'Fattoush',
    price:'2600',
    ingredients:'pepper, tomato, cucumber, lettuce, feta',

  },
  {
    id: 13,
    subVariant:'food',
    variant: 'Salads',
    counter:'0',
    title:'Caesar Salad',
    price:'3000',
    ingredients:'Chicken breast, lettuce, parmesan, tomato, Caesar dressing',
  },
  {
    id: 14,
    subVariant:'food',
    variant: 'Salads',
    counter:'0',
    title:'Caesar Shrimp Salad',
    price:'4600',
    ingredients:'shrimp, lettuce, parmesan, tomato, Caesar dressing',
  },
  {
    id: 15,
    subVariant:'food',
    variant: 'Salads',
    counter:'0',
    title:'Cabbage Tuna Salad',
    price:'2600',
    ingredients:'Tuna, Cabbage, onion, corn, dressing',
  },
  {
    id: 16,
    subVariant:'food',
    variant: 'Salads',
    counter:'0',
    title:'Avocado Salad',
    price:'3000',
    ingredients:'Avocado, lettuce, mangold, rucola, broccoli, quinoa, dressing',
  },
  {
    id: 17,
    subVariant:'food',
    variant: 'Salads',
    counter:'0',
    title:'Steak Salad',
    price:'4600',
    ingredients:'beef tenderloin, zucchini, lettuce, mangold, rucola, cucumber, dressing',
  },
  {
    id: 18,
    subVariant:'food',
    variant: 'Salads',
    counter:'0',
    title:'Prosciutto Salad',
    price:'3500',
    ingredients:'prosciutto, feta, pear, lettuce, mangold, rucola, balsamic dressing',
  },
  {
    id: 19,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Grilled Cheese',
    price:'1800',
    ingredients:'Toasted bread, mozzarella, chedar cheese Served with special tomato sauce',
  },
  {
    id: 20,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Club Sandwich',
    price:'2700',
    ingredients:'chicken breast, mozzarella, lettuce, cucumber, tomato Served with fries',
  },
  {
    id: 21,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Chicken Shawarma',
    price:'2500',
    ingredients:'Chicken breast, tomato, pickles Served with fries &amp; garlic sauce',
  },
  {
    id: 22,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Caesar Wrap',
    price:'2300',
    ingredients:'Chicken breast, Lettuce, tomato, parmesan, Caesar dressing Served with fries',
  },
  {
    id: 23,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Cheese Burger',
    price:'3000',
    ingredients:'beef, chedar cheese, pickles, onion, sauce Served with fries',
  },
  {
    id: 24,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Double Cheese Burger',
    price:'4000',
    ingredients:'beef, double chedar cheese, pickles, onion, sauce Served with fries',
  },
  {
    id: 25,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Crispy Chicken Burger',
    price:'2800',
    ingredients:'Crispy chicken, cheese, lettuce, pickles, sauce Served with fries',
  },
  {
    id: 26,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Chicken Quesadilla',
    price:'3200',
    ingredients:'chicken breast, Bell pepper, mozzarella Served with salsa &amp; sour cream',
  },
  {
    id: 27,
    subVariant:'food',
    variant: 'Sandwiches',
    counter:'0',
    title:'Beef Quesadilla',
    price:'4000',
    ingredients:'Beef, mozarella Served with salsa &amp; sour cream',
  },
  {
    id: 28,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'Shrimp Pad Thai',
    price:'4200',
    ingredients:'Shrimp, noodles, peanut, pad thai sauce, eggs',
  },
  {
    id: 29,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'Mussels',
    price:'4200',
    ingredients:'Mussels, rockford sauce',
  },
  {
    id: 30,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'Sweet &amp; Sour Chicken',
    price:'3200',
    ingredients:'chicken breast, pepper, pineapple, sweet &amp; sour sauce Served with Rice',
  },
  {
    id: 31,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'Chicken Teriyaki-',
    price:'3000',
    ingredients:'chicken breast, teriyaki sauce Served with Rice',
  },
  {
    id: 32,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'Chicken Curry',
    price:'3500',
    ingredients:'chicken breast, special curry sauce Served with Rice',
  },
  {
    id: 33,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'Grilled Chicken',
    price:'2800',
    ingredients:'Grilled chicken breast Served with grilled vegetables & special sauce',
  },
  {
    id: 34,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'Filet Mignon',
    price:'6000',
    ingredients:'beef tenderloin Served with grilled vegetables & special sauce',
  },
  {
    id: 35,
    subVariant:'food',
    variant: 'Main Course',
    counter:'0',
    title:'BBQ Mix',
    price:'5000',
    ingredients:'chicken, beef, pork Served with bbq bread, fries & garlic sauce',
  },
  {
    id: 36,
    subVariant:'food',
    variant: 'Sauces & Extras',
    counter:'0',
    title:'Shrimp (100 gr.)',
    price:'2300',
    ingredients:'',
  },
  {
    id: 37,
    subVariant:'food',
    variant: 'Sauces & Extras',
    counter:'0',
    title:'Cheese Sauce',
    price:'500',
    ingredients:'',
  },
  {
    id: 38,
    subVariant:'food',
    variant: 'Sauces & Extras',
    counter:'0',
    title:'Jalapeno',
    price:'300',
    ingredients:'',
  },
  {
    id: 39,
    subVariant:'food',
    variant: 'Sauces & Extras',
    counter:'0',
    title:'Ketchup',
    price:'200',
    ingredients:'',
  },
  {
    id: 40,
    subVariant:'food',
    variant: 'Sauces & Extras',
    counter:'0',
    title:'Mayonnaise',
    price:'200',
    ingredients:'',
  },
  {
    id: 41,
    subVariant:'food',
    variant: 'Sauces & Extras',
    counter:'0',
    title:'Sriracha hot sauce',
    price:'200',
    ingredients:'',
  },
  {
    id: 42,
    subVariant:'food',
    variant: 'Sauces & Extras',
    counter:'0',
    title:'Sour Cream',
    price:'200',
    ingredients:'',
  },
  {
    id: 43,
    subVariant:'food',
    variant: 'Desert',
    counter:'0',
    title:'Desert of The Day',
    price:'1500',
    ingredients:'',
  },
  {
    id: 44,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Evangelista',
    price:'4000',
    ingredients:'Rhubarb Gin, CuminLiquer,fresh Lemon Juice, Simple Syrup, Ginger Ale',
  },
  {
    id: 45,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Ocean Sunset',
    price:'2600',
    ingredients:'Armenian Brandy, Peach Liqueur,Fresh lemon Juice, Simple Syrup, Mango Juice',
  },
  {
    id: 46,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Inna',
    price:'3000',
    ingredients:'Gin, Orange Liqueur, Aromatic bitters, Fresh Lemon Juice, Simple Syrup, Egg White',
  },
  {
    id: 47,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Whiskey Smash',
    price:'2600',
    ingredients:'Bourbon, Fresh Lemon Juice, Simple Syrup, Lemon Peel, Mint',
  },
  {
    id: 48,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Passion Skyline',
    price:'3000',
    ingredients:'Rum, Coconut Liqueur, Fresh Lemon Juice, Simple Syrup, Pineapple Juice, Mango Juice',
  },
  {
    id: 49,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Seabuck',
    price:'3000',
    ingredients:'Sea Buckthorn Vodka, Sea Buckthorn Liqueur, Fresh Lemon Juice',
  },
  {
    id: 50,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Cherry Mery',
    price:'3000',
    ingredients:'Rum, Cherry Liqueur, Aromatic Bitters, Fresh lemon Juice, Simple Syrup, Cherry Juice',
  },
  {
    id: 51,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Pink Love',
    price:'2400',
    ingredients:'Pink Gin, Fresh Lemon Juice, Simple Syrup, Grapefruit Soda',
  },
  {
    id: 52,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Morning Sex',
    price:'3000',
    ingredients:'Cream Liqueur, Coffiee Liqueur, Hazeinut Liqueur, Milk Cream',
  },
  {
    id: 53,
    subVariant:'drinks',
    variant: 'Cocktails',
    counter:'0',
    title:'Three In One',
    price:'2400',
    ingredients:'Bitter Liqueur, Aromatic Bitters, Fresh Lemon Juice, Simple Syrup',
  },
  {
    id: 54,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Jack Daniels',
    price:'2700',
    ingredients:'',
  },
  {
    id: 55,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Jack Daniels Honey',
    price:'2700',
    ingredients:'',
  },
  {
    id: 56,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Makers Mark',
    price:'4000',
    ingredients:'',
  },
  {
    id: 57,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Wild Turkey',
    price:'2500',
    ingredients:'',
  },
  {
    id: 58,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Jim Beam White',
    price:'2500',
    ingredients:'',
  },
  {
    id: 59,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Chivas Regal 12',
    price:'3000',
    ingredients:'',
  },
  {
    id: 60,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Glen Moray',
    price:'4500',
    ingredients:'',
  },
  {
    id: 61,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Black Label',
    price:'3500',
    ingredients:'',
  },
  {
    id: 62,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Jameson',
    price:'2500',
    ingredients:'',
  },
  {
    id: 63,
    subVariant:'drinks',
    variant: 'Whiskey',
    counter:'0',
    title:'Akashi Red',
    price:'4000',
    ingredients:'',
  },
  {
    id: 64,
    subVariant:'drinks',
    variant: 'Rum',
    counter:'0',
    title:'Bacardi White',
    price:'2500',
    ingredients:'',
  },
  {
    id: 65,
    subVariant:'drinks',
    variant: 'Rum',
    counter:'0',
    title:'Bacardi Black',
    price:'2500',
    ingredients:'',
  },
  {
    id: 66,
    subVariant:'drinks',
    variant: 'Rum',
    counter:'0',
    title:'Bacardi Oakheart',
    price:'2000',
    ingredients:'',
  },
  {
    subVariant:'drinks',
    id: 67,
    variant: 'Gin',
    counter:'0',
    title:'Armenian Gin',
    price:'1500',
    ingredients:'',
  },
  {
    id: 68,
    subVariant:'drinks',
    variant: 'Gin',
    counter:'0',
    title:'Monkey 47',
    price:'5500',
    ingredients:'',
  },
  {
    id: 69,
    subVariant:'drinks',
    variant: 'Gin',
    counter:'0',
    title:'Hendricks',
    price:'3500',
    ingredients:'',
  },
  {
    id: 70,
    subVariant:'drinks',
    variant: 'Gin',
    counter:'0',
    title:'Bombay Sapphire',
    price:'2100',
    ingredients:'',
  },
  {
    id: 71,
    subVariant:'drinks',
    variant: 'Gin',
    counter:'0',
    title:'Beefeater',
    price:'1600',
    ingredients:'',
  },
  {
    id: 72,
    subVariant:'drinks',
    variant: 'Gin',
    counter:'0',
    title:'Junimperium',
    price:'3500',
    ingredients:'',
  },
  {
    id: 73,
    subVariant:'drinks',
    variant: 'Gin',
    counter:'0',
    title:'Juniperium Rhubarb',
    price:'3500',
    ingredients:'',
  },
  {
    id: 74,
    subVariant:'drinks',
    variant: 'Vodka',
    counter:'0',
    title:'Grey Goose',
    price:'4000',
    ingredients:'',
  },
  {
    id: 75,
    secondId: 1001,
    subVariant:'drinks',
    variant: 'Vodka',
    counter:'0',
    title:'Absolut',
    price:'1500',
    secondCounter:'0',
    secondPrice:'15000',
  },
  {
    id: 76,
    subVariant:'drinks',
    variant: 'Vodka',
    counter:'0',
    title:'Tito’s Handmade',
    price:'2000',
    ingredients:'',
  },
  {
    id: 77,
    subVariant:'drinks',
    variant: 'Vodka',
    counter:'0',
    title:'Tsar',
    price:'1000',
    ingredients:'',
  },
  {
    id: 79,
    subVariant:'drinks',
    variant: 'Vermouth',
    counter:'0',
    title:'Martini Bianco',
    price:'1200',
    ingredients:'',
  },
  {
    id: 80,
    subVariant:'drinks',
    variant: 'Vermouth',
    counter:'0',
    title:'Martini Extra Dry',
    price:'1200',
    ingredients:'',
  },
  {
    id: 81,
    subVariant:'drinks',
    variant: 'Vermouth',
    counter:'0',
    title:'Martini Rosso',
    price:'1200',
    ingredients:'',
  },
  {
    id: 78,
    subVariant:'drinks',
    variant: 'Vermouth',
    counter:'0',
    title:'Martini Fiero',
    price:'1500',
    ingredients:'',
  },
  {
    id: 82,
    subVariant:'drinks',
    variant: 'Tequila',
    counter:'0',
    title:'Sierra',
    price:'1800',
    ingredients:'',
  },
  {
    id: 83,
    subVariant:'drinks',
    variant: 'Tequila',
    counter:'0',
    title:'Patron Silver',
    price:'4500',
    ingredients:'',
  },
  {
    id: 84,
    subVariant:'drinks',
    variant: 'Tequila',
    counter:'0',
    title:'Don Julio Anejo',
    price:'4500',
    ingredients:'',
  },
  {
    id: 85,
    subVariant:'drinks',
    variant: 'Tequila',
    counter:'0',
    title:'Don Julio Reposado',
    price:'4000',
    ingredients:'',
  },
  {
    id: 86,
    subVariant:'drinks',
    variant: 'Tequila',
    counter:'0',
    title:'Olmeca Gold',
    price:'2200',
    ingredients:'',
  },
  {
    id: 87,
    subVariant:'drinks',
    variant: 'Tequila',
    counter:'0',
    title:'Olmeca Blanco',
    price:'2000',
    ingredients:'',
  },
  {
    id: 88,
    subVariant:'drinks',
    variant: 'Brandy & Cognac',
    counter:'0',
    title:'Ararat Nairi 20',
    price:'7000',
    ingredients:'',
  },
  {
    id: 89,
    subVariant:'drinks',
    variant: 'Brandy & Cognac',
    counter:'0',
    title:'Ararat Akhtamar 10',
    price:'3500',
    ingredients:'',
  },
  {
    id: 90,
    subVariant:'drinks',
    variant: 'Brandy & Cognac',
    counter:'0',
    title:'Ararat Ani 7',
    price:'2200',
    ingredients:'',
  },
  {
    id: 91,
    subVariant:'drinks',
    variant: 'Brandy & Cognac',
    counter:'0',
    title:'Ararat 5',
    price:'1500',
    ingredients:'',
  },
  {
    id: 92,
    subVariant:'drinks',
    variant: 'Brandy & Cognac',
    counter:'0',
    title:'Hennessy V.S.O.P',
    price:'6000',
    ingredients:'',
  },
  {
    id: 93,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Cointreau',
    price:'2200',
    ingredients:'',
  },
  {
    id: 94,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Kristall Kummel',
    price:'2000',
    ingredients:'',
  },
  {
    id: 95,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Amaro Montenegro',
    price:'2500',
    ingredients:'',
  },
  {
    id: 96,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Amaro Di Angostura',
    price:'2000',
    ingredients:'',
  },
  {
    id: 97,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Villa Massa',
    price:'2000',
    ingredients:'',
  },
  {
    id: 98,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Campari',
    price:'1800',
    ingredients:'',
  },
  {
    id: 99,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Frangelico',
    price:'2000',
    ingredients:'',
  },
  {
    id: 100,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Becherovka',
    price:'1500',
    ingredients:'',
  },
  {
    id: 101,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Malibu',
    price:'1600',
    ingredients:'',
  },
  {
    id: 102,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Baileys',
    price:'2000',
    ingredients:'',
  },
  {
    id: 103,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Borghetti',
    price:'2000',
    ingredients:'',
  },
  {
    id: 104,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Kahlua',
    price:'1500',
    ingredients:'',
  },
  {
    id: 105,
    subVariant:'drinks',
    variant: 'Liqueur & Bitters',
    counter:'0',
    title:'Jagermeister',
    price:'1500',
    ingredients:'',
  },
  {
    id: 107,
    subVariant:'drinks',
    variant: 'Champagne & Sparkling Wine',
    counter:'0',
    title:'Louis Roederer Cristal (Champagne)',
    price:'160000',
    ingredients:'',
  },
  {
    id: 108,
    subVariant:'drinks',
    variant: 'Champagne & Sparkling Wine',
    counter:'0',
    title:'G.H.Mumm Cordon Rouge (Champagne)',
    price:'55000',
    ingredients:'',
  },
  {
    id: 109,
    secondId: 1002,
    subVariant:'drinks',
    variant: 'Champagne & Sparkling Wine',
    counter:'0',
    title:'Zonin Prosecco',
    price:'1800',
    secondCounter:'0',
    secondPrice:'10000',
    ingredients:'',
  },
  {
    id: 110,
    secondId: 1003,
    subVariant:'drinks',
    variant: 'Champagne & Sparkling Wine',
    counter:'0',
    title:'Zonin Prosecco Rose – 1800/10,000',
    price:'1800',
    secondCounter:'0',
    secondPrice:'10000',
    ingredients:'',
  },
  {
    id: 111,
    variant: 'Champagne & Sparkling Wine',
    counter:'0',
    subVariant:'drinks',
    title:'Takar Brut',
    price:'8000',
    ingredients:'',
  },
  {
    id: 112,
    subVariant:'drinks',
    variant: 'Champagne & Sparkling Wine',
    counter:'0',
    title:'Takar Brut – Rose',
    price:'9000',
    ingredients:'',
  },
  {
    id: 113,
    subVariant:'drinks',
    secondId: 1004,
    variant: 'Wine',
    counter:'0',
    title:'Armas Red',
    price:'1500',
    secondCounter:'0',
    secondPrice:'7000',
    ingredients:'',
  },
  {
    id: 114,
    subVariant:'drinks',
    secondId: 1005,
    variant: 'Wine',
    counter:'0',
    title:'Keerk White',
    price:'1300',
    secondCounter:'0',
    secondPrice:'6000',
    ingredients:'',
  },
  {
    id: 115,
    subVariant:'drinks',
    secondId: 1006,
    variant: 'Wine',
    counter:'0',
    title:'Armas Rose',
    price:'1400',
    secondCounter:'0',
    secondPrice:'6000',
    ingredients:'',
  },
  {
    id: 116,
    subVariant:'drinks',
    secondId: 1007,
    variant: 'Wine',
    counter:'0',
    title:'Takar Red',
    price:'1500',
    secondCounter:'0',
    secondPrice:'7000',
    ingredients:'',
  },
  {
    id: 117,
    subVariant:'drinks',
    secondId: 1008,
    variant: 'Wine',
    counter:'0',
    title:'Takar White',
    price:'1300',
    secondCounter:'0',
    secondPrice:'6000',
    ingredients:'',
  },
  {
    id: 118,
    subVariant:'drinks',
    secondId: 1009,
    variant: 'Wine',
    counter:'0',
    title:'Takar Rose',
    price:'1400',
    secondCounter:'0',
    secondPrice:'6500',
    ingredients:'',
  },
  {
    id: 119,
    subVariant:'drinks',
    secondId: 1010,
    variant: 'Wine',
    counter:'0',
    title:'Hin Areni Red',
    price:'1300',
    secondCounter:'0',
    secondPrice:'6000',
    ingredients:'',
  },
  {
    id: 120,
    subVariant:'drinks',
    secondId: 1011,
    variant: 'Wine',
    counter:'0',
    title:'Hin Areni White',
    price:'1500',
    secondCounter:'0',
    secondPrice:'7000',
    ingredients:'',
  },
  {
    id: 121,
    subVariant:'drinks',
    secondId: 1012,
    variant: 'Wine',
    counter:'0',
    title:'Hin Areni Rose',
    price:'1300',
    secondCounter:'0',
    secondPrice:'6000',
    ingredients:'',
  },
  {
    id: 122,
    subVariant:'drinks',
    variant: 'Wine',
    counter:'0',
    title:'Tariri White',
    price:'12000',
  },
  {
    id: 123,
    subVariant:'drinks',
    variant: 'Wine',
    counter:'0',
    title:'Tariri White',
    price:'9000',
  },
  {
    id: 124,
    subVariant:'drinks',
    variant: 'Beer',
    counter:'0',
    title:'Dargett',
    price:'1300',
    ingredients:'',
  },
  {
    id: 125,
    subVariant:'drinks',
    variant: 'Beer',
    counter:'0',
    title:'Corona',
    price:'1300',
    ingredients:'',
  },
  {
    id: 126,
    subVariant:'drinks',
    variant: 'Beer',
    counter:'0',
    title:'Heineken',
    price:'1300',
    ingredients:'',
  },
  {
    id: 127,
    subVariant:'drinks',
    variant: 'Beer',
    title:'Stela',
    counter:'0',
    price:'1300',
    ingredients:'',
  },

  {
    id: 128,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    title:'Water',
    counter:'0',
    price:'400',
    ingredients:'',
  },
  {
    id: 129,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    counter:'0',
    title:'Sparkling Water',
    price:'400',
    ingredients:'',
  },
  {
    id: 130,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    counter:'0',
    title:'Cola/Fanta/sprite',
    price:'500',
    ingredients:'',
  },
  {
    id: 131,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    title:'Juice',
    counter:'0',
    price:'850',
    ingredients:'',
  },
  {
    id: 132,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    counter:'0',
    title:'Energy Drink',
    price:'1500',
    ingredients:'',
  },
  {
    id: 133,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    counter:'0',
    title:'Schweppes',
    price:'700',
    ingredients:'',
  },
  {
    id: 134,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    counter:'0',
    title:'Fever Tree',
    price:'1300',
    ingredients:'',
  },
  {
    id: 135,
    subVariant:'drinks',
    variant: 'Soft Drinks',
    counter:'0',
    title:'Three Cents',
    price:'1300',
    ingredients:'',
  },
  {
    id: 136,
    subVariant:'drinks',
    variant: 'Mocktails',
    counter:'0',
    title:'Green Forest',
    price:'2000',
    ingredients:'kiwi puree, Fresh lemon juice, Aegean tonic',
  },
  {
    id: 137,
    subVariant:'drinks',
    variant: 'Mocktails',
    counter:'0',
    title:'Tropicana',
    price:'2000',
    ingredients:'mango puree, Pineapple juice, fresh lemon juice',
  },
  {
    id: 138,
    subVariant:'drinks',
    variant: 'Mocktails',
    counter:'0',
    title:'Lemonade',
    price:'2000',
    ingredients:'',
  },
  {
    id: 139,
    subVariant:'drinks',
    variant: 'Tea & Coffee',
    counter:'0',
    title:'Black/Green Tea',
    price:'1300',
    ingredients:'',
  },
  {
    id: 140,
    subVariant:'drinks',
    variant: 'Tea & Coffee',
    counter:'0',
    title:'Ice Tea',
    price:'1500',
    ingredients:'',
  },
  {
    id: 141,
    subVariant:'drinks',
    variant: 'Tea & Coffee',
    counter:'0',
    title:'Armenian Coffee',
    price:'600',
    ingredients:'',
  },
  {
    id: 142,
    subVariant:'drinks',
    variant: 'Tea & Coffee',
    counter:'0',
    title:'Espresso',
    price:'1000',
    ingredients:'',
  },
  {
    id: 143,
    subVariant:'drinks',
    variant: 'Tea & Coffee',
    counter:'0',
    title:'Americano',
    price:'1000',
    ingredients:'',
  },
  {
    id: 144,
    subVariant:'drinks',
    variant: 'Tea & Coffee',
    counter:'0',
    title:'Cappuccino',
    price:'1500',
    ingredients:'',
  },
  {
    id: 145,
    subVariant:'drinks',
    variant: 'Tea & Coffee',
    counter:'0',
    title:'Latte Macchiato',
    price:'1500',
    ingredients:'',
  },
  {
    id: 146,
    subVariant:'drinks',
    variant: 'Snacks',
    counter:'0',
    title:'Go Nuts',
    price:'3000',
    ingredients:'Pistachio, peanut, almond, olives, pickles, chips',
  },
  {
    id: 147,
    subVariant:'drinks',
    variant: 'Snacks',
    counter:'0',
    title:'Veggie Sticks',
    price:'1000',
    ingredients:'Cucumber, carrots',
  },
  {
    id: 148,
    subVariant:'drinks',
    variant: 'Snacks',
    title:'Chips',
    counter:'0',
    price:'800',
    ingredients:'',
  },
  {
    id: 149,
    subVariant:'drinks',
    variant: 'Snacks',
    title:'Lemon',
    counter:'0',
    price:'700',
    ingredients:'',
  },
  {
    id: 150,
    subVariant:'drinks',
    variant: 'Snacks',
    counter:'0',
    title:'Olives',
    price:'800',
    ingredients:'',
  },
]